### ISSUE TITLE
[S3 - PB11] Feedback

### ISSUE THREAD

**Issue by sttan213** [SI-RPL-2022/SI4303_E_HUTANLESTARI#13]
User dapat memberikan feedback kepada website HutanLestari

**Comment by sttan213** [comment]
Untuk fitur feedback terdapat pada Footer website yang mana user dapat memberikan feedback kepada website HutanLestari. Berikut dilampirkan Mockup, Use Case Description, dan Activity Diagram :

1. Mockup 
![WhatsApp Image 2022-06-06 at 7 09 10 PM](https://user-images.githubusercontent.com/92033843/172164312-72e2af07-139f-4ee2-9921-32bd6c24cb8e.jpeg)

2. Use Case Description
![Use case description feedback](https://user-images.githubusercontent.com/92033843/172164335-efb00277-7180-44e6-b281-ea675c1672d7.png)

3. Activity Diagram
![Activity Diagram Feedback](https://user-images.githubusercontent.com/92033843/172164360-663efa5e-be37-4947-8b12-0a59af15f24e.png)

**Comment by ekkynovrizalam** [comment]
dibuatkan fitur untuk melihat list feedback di sisi admin

**Comment by sttan213** [comment]
https://user-images.githubusercontent.com/92033843/174832250-b4c4b7fe-7774-49cc-bb6f-1ca91cbe2f1d.mp4
