### ISSUE TITLE
[S3 - PB7] Profil user

### ISSUE THREAD

**Issue by reginatasya** [SI-RPL-2022/SI4303_E_HUTANLESTARI#8]
user membuka tampilan dashboar untuk melihat akun pengguna

**Comment by reginatasya** [comment]
berikut merupakan tampilan dashboard user :
![Dashboard user](https://user-images.githubusercontent.com/76657376/165133671-0d24f212-eba7-4fa2-afd5-12f3854f1a89.png)

**Comment by reginatasya** [comment]
berikut merupakan usecase description dan activity diagram :
Usecase description:
<img width="301" alt="image" src="https://user-images.githubusercontent.com/76657376/165144995-b408281c-229f-4430-84e2-76d3ab1e6109.png">

Activity Diagram:
![userss dash](https://user-images.githubusercontent.com/76657376/165144877-58ee7547-5b7e-4506-8883-3a85ebaa3ae2.png)

**Comment by reginatasya** [comment]
SETTING BAGIAN PROFILE USER:

berikut merupakan mockup setting
![Setting (1)](https://user-images.githubusercontent.com/76657376/172279514-9f1f5e53-cb6c-4983-9153-c99be9fe1cab.png)
![Setting](https://user-images.githubusercontent.com/76657376/172279517-51806b77-1d63-4a8f-955f-baf20c16c0e2.png)

berikut merupakan diagram activity  setting
![setting](https://user-images.githubusercontent.com/76657376/172279931-41d95f55-8b44-4aaf-8fc5-dc9120bc6117.jpg)

berikut merupakan usecase setting
<img width="301" alt="image" src="https://user-images.githubusercontent.com/76657376/172282156-e441845e-4f4f-4e62-bd71-1c08dced4589.png">

**Comment by ekkynovrizalam** [comment]
termasuk edit profile picture user

**Comment by reginatasya** [comment]
https://user-images.githubusercontent.com/76657376/174826658-87ab8fbe-4c0e-4674-9a38-1aeddf14538c.mp4

berikut video sprint 3
