### ISSUE TITLE
[S2 - PB10] Form Relawan

### ISSUE THREAD

**Issue by emasdai** [SI-RPL-2022/SI4303_E_HUTANLESTARI#9]
form yang digunakan oleh user untuk mendaftarkan diri menjadi relawan

**Comment by emasdai** [comment]
![image](https://user-images.githubusercontent.com/43808379/165192408-cea76aff-9c81-406c-b406-a753e137f695.png)

**Comment by emasdai** [comment]
![image](https://user-images.githubusercontent.com/43808379/165192408-cea76aff-9c81-406c-b406-a753e137f695.png)

**Comment by emasdai** [comment]
Activity Diagram :
![1](https://user-images.githubusercontent.com/43808379/165192811-c6956808-cfd8-4bc3-9610-deeb558276de.jpg)

**Comment by emasdai** [comment]
Use Case Description : 
![Use Case Description 1](https://user-images.githubusercontent.com/43808379/165194003-c8d72d4f-6a96-4dd0-819a-9a8f2cb4a152.jpg)
![Use Case Description 2](https://user-images.githubusercontent.com/43808379/165194007-0d5a7055-371c-4635-98d9-25aa1fe5a643.jpg)

**Comment by emasdai** [comment]
1. MockUp
![image](https://user-images.githubusercontent.com/43808379/165207320-2e8bb17b-1d99-49ee-b43d-49cccc63c6ce.png)

2. Diagram Activity
![1](https://user-images.githubusercontent.com/43808379/165207415-3b0e7c6f-a62e-4b97-8907-f6efc53d707b.jpg)

3. Use Case Description
![Use Case Description 1](https://user-images.githubusercontent.com/43808379/165207443-1ddc6ed4-93a1-44e5-990d-27850e8cca61.jpg)
![Use Case Description 2](https://user-images.githubusercontent.com/43808379/165207448-074877b5-0be7-49a8-98f7-857d4e2df9b1.jpg)

**Comment by ekkynovrizalam** [comment]
ini bisa konfirmasi dan tolak pengajuan oleh admin

**Comment by emasdai** [comment]
Video [S2 - PB10] Form Relawan

https://user-images.githubusercontent.com/43808379/170899257-48068456-1021-4a99-8962-30085fafa5fe.mp4

**Comment by emasdai** [comment]
Video [S2 - PB10] Form Relawan

https://user-images.githubusercontent.com/43808379/170899760-c90c155c-c30d-45e4-a6b8-1685e17a25c6.mp4
